import{a as h,S as b,i as u}from"./assets/vendor-d93b82f1.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&o(m)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const y=s=>`
  <li class="gallery-card">
  <div class="container-el">
  <div class="container-img">
    <a href="${s.largeImageURL}"><img class="gallery-img" src="${s.webformatURL}" alt="${s.tags}" /></a>
  </div>  <div class="container-text">
      <p class="text-name">Likes <span class="span-numbers">${s.likes}</span></p>
      <p class="text-name">Views <span class="span-numbers">${s.views}</span></p>
      <p class="text-name">Comments <span class="span-numbers">${s.comments}</span></p>
      <p class="text-name">Downloads <span class="span-numbers">${s.downloads}</span></p>
    </div>
  </div>
</li>
  `;h.defaults.baseURL="https://pixabay.com";const f=async(s,t)=>{const a={params:{key:"45423395-a55c580a59309a3b931c40bb9",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}};return h.get("/api/",a)},l=document.querySelector(".js-form"),n=document.querySelector(".list-photo"),i=document.querySelector(".js-loader"),d=document.querySelector(".js-btn-load-more");let p=1,c="",g=0;const v=async s=>{try{if(s.preventDefault(),c=l.elements.img.value.trim(),p=1,c===""){u.error({message:"Please enter a search term."});return}l.reset(),i.classList.remove("is-hidden");const t=await f(c,p);if(t.data.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!"}),n.innerHTML="",l.reset(),d.classList.add("is-hidden");return}const a=t.data.hits.map(e=>y(e)).join("");n.innerHTML=a,g=n.querySelector("li").getBoundingClientRect().height,L.refresh(),i.classList.add("is-hidden"),d.classList.remove("is-hidden")}catch(t){console.log(t)}finally{i.classList.add("is-hidden")}},S=async s=>{try{i.classList.remove("is-hidden"),p++;const t=await f(c,p),a=t.data.hits.map(o=>y(o)).join("");if(n.insertAdjacentHTML("beforeend",a),scrollBy({top:g*2,behavior:"smooth"}),n.children.length>=t.data.totalHits){d.classList.add("is-hidden"),u.error({message:"We're sorry, but you've reached the end of search results."});return}L.refresh()}catch(t){console.log(t)}finally{i.classList.add("is-hidden")}},L=new b(".container-img a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250});l.addEventListener("submit",v);d.addEventListener("click",S);
//# sourceMappingURL=commonHelpers.js.map
